#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 IP_ADDRESS"
    exit 1
fi

ip_address=$1

ping -c 1 "$ip_address" > /dev/null

if [ $? -eq 0 ]; then
    echo "$ip_address is up!"
else
    echo "$ip_address is down!"
fi
