#!/usr/bin/env bash
# Command to make an nginx server listen on port 80, shorter version
sed -i 's/listen 8080 default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on/listen \[::\]:80 default_server ipv6only=on/' /etc/nginx/sites-enabled/default
pkill -SIGHUP nginx
