#!/usr/bin/env bash
# Display "Best School" 10 times and displays "Hi" for the 9th iteration
 
count=1
while (( count <= 10 ));
do
	echo "Best School"
	if (( count == 9 ));
	then	
		echo "Hi"
	fi
	((count++))
done
